### ISSUE TITLE
如何讲gpt用谷歌搜索以及其他相关autogpt原生自带工具配置进去呢

### ISSUE THREAD

**Issue by ywh888** [Dogtiti/AutoGPT-Next-Web#1]

**Comment by LiuElric** [comment]
autogpt原生自带工具指哪些呀？  @ywh888

**Comment by ywh888** [comment]
谷歌搜索，语音合成，gpt联网等

**Comment by LiuElric** [comment]
已经支持了联网能力参考这个里面的《联网能力配置说明》 https://autogpt-next-web.gitbook.io/autogpt-next-web/

**Comment by VectorZhao** [comment]
这里的说明：[联网配置](https://autogpt-next-web.gitbook.io/autogpt-next-web/lian-wang-neng-li-pei-zhi-shuo-ming)
autogpt只需要填写key就可以调用谷歌搜索功能，而本项目是利用第三方api来实现的吗？

**Comment by Dogtiti** [comment]
@VectorZhao autogpt可以理解是一个服务，服务端直接可以直接访问google搜索，本项目是前端项目，从浏览器角度来说访问google搜索会跨域，所以目前是调用第三方api来搜索的，不过我们也在研究如何在本项目能直接使用google的搜索，争取让大家都免费使用
