### ISSUE TITLE
[BUG] 问答无法中文化的问题

### ISSUE THREAD

**Issue by tanglu86** [Dogtiti/AutoGPT-Next-Web#106]
我通过./setup.sh --docker的方式在自己的服务器上部署了AutoGPT-Next-Web，服务运行正常，但是在使用中文提问的时候回答依然是英文，测试过程截图：
![QQ图片20230504095525](https://user-images.githubusercontent.com/38269740/236093007-0ab3c56d-82e2-402d-b446-1e004ca49d01.png)

**Comment by Dogtiti** [comment]
sync fork
