### ISSUE TITLE
1.0.4版本长时间处于"运行中"状态[BUG]

### ISSUE THREAD

**Issue by tanglu86** [Dogtiti/AutoGPT-Next-Web#109]
![1](https://user-images.githubusercontent.com/38269740/236129203-04e6bec8-350f-44d7-adbf-f86b50743570.jpg)
部署环境：
自有CentOS 7独立服务器

部署方式：
./setup.sh --docker

部署完成后访问:3000可以正常打开，但是进行任何提问都会卡住，一直处于"运行中"状态。
降级为1.0.3，使用同样的操作方式则是正常的，但是1.0.3存在回答无法汉化的问题

**Comment by flykarry** [comment]
一样，有解决办法吗？

**Comment by tanglu86** [comment]
> 一样，有解决办法吗？

我暂时没有找到解决办法……只有等大佬修复了

**Comment by Dogtiti** [comment]
已更新docker再试一下，本地运行保证自己能访问openai，需要开梯子或者代理

**Comment by mrifoxer** [comment]
我用vercel部署的也是一样的情况，只要填入token就是卡在运行中，不填token可正常使用，但会提示“由于这只是一个演示，我们的代理程序不能运行太长时间”

**Comment by LiuElric** [comment]
可以加一下我们QQ群，我刚试了一下，都没有问题，尝试部署最新版本看看？@mrifoxer

**Comment by mrifoxer** [comment]
我同步仓库后重新部署过、也把项目删除再完全部署过 都是同样的情况

**Comment by mrifoxer** [comment]
这2两种方法都是刚刚操作的

**Comment by Dogtiti** [comment]
@mrifoxer  打开控制台 看一下network 看看是什么报错，或者看下console里有没有报错 ，截图

**Comment by mrifoxer** [comment]
我现在是绑定自有域名的状态

**Comment by Dogtiti** [comment]
@mrifoxer 配置cname

**Comment by mrifoxer** [comment]
已配置cname 通过自有域名不用梯子可以正常访问项目网站，只是填入token就是卡在运行中，不填token可正常使用，但会提示“由于这只是一个演示，我们的代理程序不能运行太长时间”

**Comment by Dogtiti** [comment]
填入token 请求是走浏览器端，不填是走服务端，你填token开梯子试试，应该是这个问题，另外你可以配置访客模式，访客模式可以调整高级配置

**Comment by LiuElric** [comment]
尝试打开无痕模式看看，之前有碰到过因为缓存和梯子问题导致你这个类似的情况的

**Comment by mrifoxer** [comment]
填入token后开梯子可以正常使用。我已配置访客模式，我再找找你说的调整高级配置在哪，非常感谢您帮我定位到问题所在，谢谢~

**Comment by Dogtiti** [comment]
> 填入token后开梯子可以正常使用。我已配置访客模式，我再找找你说的调整高级配置在哪，非常感谢您帮我定位到问题所在，谢谢~

左下角设置面板，访客模式就可以调循环次数了,就不用填token就能调整高级设置，也就免了本地梯子问题

**Comment by mrifoxer** [comment]
已设置,谢谢~
