### ISSUE TITLE
[BUG] 设置页面输入API key反而不能用

### ISSUE THREAD

**Issue by lancer-wang** [Dogtiti/AutoGPT-Next-Web#114]
**Describe the bug / 描述bug**

设置页面不输入密钥还能使用，输入密钥提示

访问OpenAI API出错。请检查您的API密钥或稍后重试

**To Reproduce / 复现方式**

使用vercel部署，全程跟着教程

**Expected behavior / 期望的行为**

期望填api key也能用

**Screenshots / 截屏**

![image](https://user-images.githubusercontent.com/69783837/236365584-a326d3ca-99f8-49d9-8ee6-599943869f7b.png)

这里的密钥我也填了
![image](https://user-images.githubusercontent.com/69783837/236365731-26ce7817-4a23-41da-8b12-7fa50164b395.png)

**Device information / 设备信息**

使用的最新版本

baada125ffe8b6a817acc8219cc97c6ed68d229c

![image](https://user-images.githubusercontent.com/69783837/236365859-81be616d-37d7-45b9-9211-ce48c27ed1ec.png)

![image](https://user-images.githubusercontent.com/69783837/236365901-6ce874ac-68a1-4fec-b410-4732cbbcaf15.png)

**Comment by Dogtiti** [comment]
我刚试了一下是可以的，你可以在我们主站上试一下看看，如果还有问题可以给点更详细的信息

**Comment by lancer-wang** [comment]
解决了，本地居然也要开代理才行

**Comment by lancer-wang** [comment]
要把这个openapi.com 加到代理软件

![image](https://user-images.githubusercontent.com/69783837/236591798-4f2cd757-c4a9-4d20-8c92-c72ccfd78906.png)

**Comment by Dogtiti** [comment]
是这样，本质还是从浏览器发送的请求，需要走代理



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月6日(周六) 上午9:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Dogtiti/AutoGPT-Next-Web] [BUG] 设置页面输入API key反而不能用 (Issue #114)




 
要把这个openapi.com 加到代理软件
