### ISSUE TITLE
[BUG]在输入名称/目标的时候 回车键 会错误触发“停止代理程序”

### ISSUE THREAD

**Issue by LiYeLin** [Dogtiti/AutoGPT-Next-Web#122]
**Describe the bug / 描述bug**
在输入名称的时候 会错误触发“停止代理程序”

名称和目标的输入框中，在输入法中敲击回车的时候 会直接触发“停止代理程序” 但是本意只是想直接输入某个英文字符。

**To Reproduce / 复现方式**
首页 在名称/目标输入框中，简单输入“成为AI工程师”，其中“AI”使用中文输入法输入，并且通过回车键直接录入

**Expected behavior / 期望的行为**
焦点在输入框的时候 回车不会触发按钮
**Screenshots / 截屏**

**Device information / 设备信息**
M1 芯片 macbook pro 13寸
  设备，比如：iphone6
  macos 12 5 1 
- Browser [e.g. safari]
  chrome
  最新

**Comment by NateCC0902** [comment]
> @LiuElric 这里我觉得还是ctrl+enter 好 ，普通回车就换行或者其他作用

認同 用enter 實在太容易誤觸發了

**Comment by Dogtiti** [comment]
@NateCC0902 那来个pr :rofl:

**Comment by LiuElric** [comment]
之前提过了，可以合一下，我们上次结论是可以合
