### ISSUE TITLE
[FEAT] 增加本地存储对话的能力

### ISSUE THREAD

**Issue by Dogtiti** [Dogtiti/AutoGPT-Next-Web#124]
### 描述 / Description
未启用登录功能的可以将对话存储在localstorage中

**Comment by Dogtiti** [comment]
@LiuElric 评估一下这个是否有必要，目前登录能力对绝大多数人来说比较困难

**Comment by LiuElric** [comment]
网络存储的可以，本地感觉意义不大，AutoGPT，跟ChatGPT不太一样，重新部署就是重新跑，会覆盖之前的，保留一个对话也没太大意义

**Comment by VectorZhao** [comment]
保留对话内容没有意义？
可以免去重新设定goal的麻烦，单凭这一点，意义就很大。个人建议。
