### ISSUE TITLE
[Suggestions] 使用docker部署后无法打开网络搜索

### ISSUE THREAD

**Issue by gallonyin** [Dogtiti/AutoGPT-Next-Web#128]
使用docker部署后无法打开网络搜索，提示成本原因等。
是否可以通过使用本服务器直接网络搜索，或者只是忘了提供开关设置。

**Comment by Dogtiti** [comment]
docker还没更新，稍微等一等

**Comment by gallonyin** [comment]
@Dogtiti 测试发现并没有更新，请检查一下镜像
