### ISSUE TITLE
[BUG]使用访客密码访问回答仍然受到限制

### ISSUE THREAD

**Issue by cakexxx** [Dogtiti/AutoGPT-Next-Web#130]
使用访客密码访问，在回答之后仍然显示回答受限制，在对话的最后会出现如下对话。
![image](https://user-images.githubusercontent.com/49086951/236685732-4c53c24e-ddf1-480e-b6b0-73c7d8a6bcb0.png)

**Comment by Dogtiti** [comment]
文案问题 暂时不影响使用 之前是为了面向部署到网站上消耗key过大的问题，访客模式现在开放了所有设置 回头优化一下提示文案
