### ISSUE TITLE
請儘快重新生成您的金鑰，以避免任何潛在的傷害。

### ISSUE THREAD

**Issue by ErosChan1023** [Dogtiti/AutoGPT-Next-Web#153]
Please regenerate your key as soon as possible to avoid any potential harm.

_Originally posted by @Dogtiti in https://github.com/Dogtiti/AutoGPT-Next-Web/issues/150#issuecomment-1543892731_
            如何生成

**Comment by Dogtiti** [comment]
?? 你为什么一直在提issue啊
