### ISSUE TITLE
deno代理设置，接口请求响应401

### ISSUE THREAD

**Issue by xdk123456** [Dogtiti/AutoGPT-Next-Web#199]
### Please check that this issue hasn't been reported before
请检查之前没有报告过此问题

- [X] I searched previous [Bug Reports](https://github.com/Dogtiti/AutoGPT-Next-Web/issues?q=is%3Aissue+is%3Aopen+label%3Abug) didn't find any similar reports.我搜索了以前的 [Bug Reports](https://github.com/Dogtiti/AutoGPT-Next-Web/issues?q=is%3Aissue+is%3Aopen+label%3Abug) 没有找到任何类似的报告。

### Expected Behavior/预期行为

deno代理openai接口，可支持国内正常访问。

### Current behaviour/当前行为

通过ercel.com创建web页面。deno代理openai接口（按教程添加好），web页面已正常添加代理。
![image](https://github.com/Dogtiti/AutoGPT-Next-Web/assets/16758422/0dd949c1-32d2-4b46-b65a-38430bff816a)

web已发起代理接口OPTIONS正常200，但POST请求则响应401。
![image](https://github.com/Dogtiti/AutoGPT-Next-Web/assets/16758422/f44ca61c-ac2a-4a5f-a4c6-4fde70d840a6)
![image](https://github.com/Dogtiti/AutoGPT-Next-Web/assets/16758422/2946efba-01d8-499d-bf09-0042c2b293ca)

当前web设置了openai密钥和代理，密钥仍为openai的密钥：sk-xxxx，请问是否需要额外设置？

### Steps to reproduce/重现步骤

通过ercel.com创建web页面。deno代理openai接口（按教程添加好），web页面已正常添加代理。

### Which Operating Systems are you using?您使用的是哪种操作系统？

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Acknowledgements致谢

- [X] My issue title is concise, descriptive, and in title casing.我的问题标题简明扼要，具有描述性，并且使用标题框
- [X] I have searched the existing issues to make sure this bug has not been reported yet.我已经搜索了现有问题以确保尚未报告此错误。
- [X] I am using the latest version of AutoGPT-Next-Web.我使用的是最新版本的 AutoGPT-Next-Web
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.我已经为维护者提供了足够的信息来重现和诊断问题。

**Comment by Dogtiti** [comment]
使用的 azure？ 那得填 azure 的密钥
