### ISSUE TITLE
這個不是AutoGPT只是AgentGPT的中文版

### ISSUE THREAD

**Issue by Xiaobonor** [Dogtiti/AutoGPT-Next-Web#20]

**Comment by LiuElric** [comment]
你好，感谢关注
1. AutoGPT-Next-Web 这个项目是来源于 AgentGPT，AgentGPT 其实也是 AutGPT 的 web UI 版本，我们团队提供了 i18n 方案以及一键部署能力，更方便大家自己搭建使用
2. AgentGPT 的一键部署能力和 18n (有个哥们正在做)也是来源于我们的项目，我们本身也在为 AgentGPT 贡献代码AgentGPT 团队，也邀请我们加入他们团队做本地化版本
3. 我们目标是持续输出对国内用户友好的功能和界面(包括但不限于微信登录等），让大家更易用

**Comment by LiuElric** [comment]
Thanks for the discussion ! LangChain is better at building its own application and process control, while AutoGPT is more about having autonomous agents.
Auto stands for automatic. Whether it uses langchain as the bottom layer or the technology of the AutoGPT project as the bottom layer, they all have the ability to perform operations automatically. I think they all deserve the word Auto

**Comment by lzskyline** [comment]
这个就是为了给他们星球引流、骗小白的项目
部署能力是vercel提供的，他们只是弄了个模板，我试了一下还是跟原版一样需要输入各种除了openai key之外的配置，根本没实现他们所说的“一键部署”
中文语言支持也是原版本就有的：https://agentgpt.reworkd.ai/zh

他们反而花了大精力在里面植入各种引流广告
