### ISSUE TITLE
添加保存以及share的功能

### ISSUE THREAD

**Issue by leizhuray** [Dogtiti/AutoGPT-Next-Web#200]
### ⚠️ Please check that this feature request hasn't been suggested before.请检查之前是否没有建议过此功能请求。

- [X] I searched previous [Ideas in issue](https://github.com/Dogtiti/AutoGPT-Next-Web/issues) didn't find any similar feature requests.我搜索了之前的 [Ideas in issue](https://github.com/Dogtiti/AutoGPT-Next-Web/issues) 没有找到任何类似的功能请求。

### 🔖 Feature description 功能说明

不知道是否有计划未来在运行完后在左侧添加保存的功能呢？或者类似可以通过一个链接直接share的功能，然后保持原有的格式

### ✔️ Solution 解决方案

不知道

### Acknowledgements 致谢

- [X] My issue title is concise, descriptive, and in title casing.我的问题标题简明扼要，具有描述性，并且使用标题框。
- [X] I have searched the existing issues to make sure this feature has not been requested yet.我已经搜索了现有问题以确保尚未请求此功能。
- [X] I have provided enough information for the maintainers to understand and evaluate this request.我已经为维护者提供了足够的信息来理解和评估这个请求。

**Comment by Dogtiti** [comment]
这个功能本身是有的，需要自己看代码动手集成一下，暂时没有教程

**Comment by leizhuray** [comment]
> 这个功能本身是有的，需要自己看代码动手集成一下，暂时没有教程


![image](https://github.com/Dogtiti/AutoGPT-Next-Web/assets/32698600/d8706256-3c2a-45fc-b616-f42a50fbd772)
不知道是否可以像babyagi这样存在当地

**Comment by Dogtiti** [comment]
理论是可以的但是不推荐，因为我们的任务通常情况下会很大，不像chatgpt一个问答可能没有多少文字，本地localstorage的容量是有限的，大概在5M左右，所以可能存不了几个task，此时需要使用数据库存储
