### ISSUE TITLE
韭菜项目

### ISSUE THREAD

**Issue by lzskyline** [Dogtiti/AutoGPT-Next-Web#33]
蹭chatgpt-next的名字热度，但并不能一键部署. 甚至代码都不是自己写的
抄袭https://agentgpt.reworkd.ai/zh, 还比原版多了一堆韭菜星球之类的广告
我为啥不用原版？
https://github.com/reworkd/AgentGPT

**Comment by LiuElric** [comment]
你好，感谢关注

- AutoGPT-Next-Web 这个项目是来源于 AgentGPT，AgentGPT 其实也是 AutoGPT 的 web UI 版本，我们提供了 i18n 方案以及vercel一键部署能力，更方便大家自己搭建使用
- AgentGPT 的一键部署能力和 i18n 本地化能力也是来源于我们的项目，我们本身也在为 AgentGPT 贡献代码，AgentGPT 官方也邀请加入他们开发团队
- 我们目标是持续输出对国内用户友好的功能和界面（包括但不限于微信登录等），让大家更易用

如果您觉得一键部署哪里不能执行，欢迎给我们提issue

**Comment by lzskyline** [comment]
其一，AutoGPT-Next-Web 名字蹭 ChatGPT-Next-Web的热度。后者是完全自己开发的前端且体验良好，你们是直接把Agent GPT的前端拿来植入了一车广告引流链接
其二，你们宣传的所谓一键部署，也是模仿ChatGPT-Next-Web基于vercel实现的，但后者真正做到了一键部署，只需要输入openai key和可选的认证密码就能完成搭建，不需要考虑任何技术上的事情，如下：
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/9845170/234164370-9b8b4986-04bb-4bdc-89c5-8aa4e6336926.png">
而你们的需要填写很多部署上的配置，并且没有任何解释说明（我理解之所以会这样的原因是，被你们抄袭且你们没有在项目中注明的原版AgentGPT项目要求填入这些配置，你们只是原样照搬过来甚至不愿意简化）这违背了一键部署的初衷，所以这个所谓的“一键部署”对新手来说并没有实际意义，甚至对于没有自己搭建过AgentGPT项目的人来说反而会引起迷惑，不知道URL指的是什么，不知道DATABASE链接的格式应该是什么样。你们也没在readme中提及，直接照搬了AgentGPT手动部署的文档
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/9845170/234164357-8de7d89f-20f4-4035-880c-defb1aecee79.png">
其三，AgentGPT本就支持中文，而且没有这么多引流链接广告。
<img width="1647" alt="image" src="https://user-images.githubusercontent.com/9845170/234164337-464b0fbd-93a8-4243-b818-861084c1fabc.png">
你摸着良心说这不是一个毫不走心的韭菜项目是啥？在github发这些是想让国际友人笑话咱们中国人么？

**Comment by LiuElric** [comment]
感谢回复
1、并没有蹭ChatGPT-Next-Web的意思，因为我们也是ChatGPT-Next-web的开发人员；如果你在Git上搜索一下，可以看到至少200个跟nextweb相关的项目
<img width="1187" alt="oLhhSyjzWL" src="https://user-images.githubusercontent.com/20209191/234168795-d2abcdc2-dda5-4ef3-9c1f-2bf69f8794c1.png">
2、感谢建议，这块我们做的确实不太好，readme里面没有说明的太清楚（改进中），由于项目的不同，最开始的时候无法做到跟ChatGPT-Next-Web一样只填写一个key，我们也在积极简化部署要求，我们理解一键部署是通过vercel能够大幅降低部署门槛
![image](https://user-images.githubusercontent.com/20209191/234168956-6c706aea-7f28-430d-8dfb-9d716dbbf2bc.png)
3、AgentGPT的中文版就是从我们项目中拿的代码，是我们先支持中文之后，AgentGPT合并过去的。。。。
<img width="825" alt="image" src="https://user-images.githubusercontent.com/20209191/234169505-7349df91-68b1-4496-bc4e-0ada0195fd70.png">

**Comment by lzskyline** [comment]
1. github上搜“GPT-Next-Web”关键字的仓库，除了ChatGPT-Next-Web就是你们了，不要跟nextweb混淆。
2. 你们现在提供出来的，就是vercel最基础的能力，并没有基于AgentGPT做什么环境的改动，甚至是readme。所以不应该叫做“一键部署”
3. 拿着混pr的截图忽悠大家是啥意思？你管文件夹名称重命名叫“拿你们的代码”？，AgentGPT的翻译都是[Cs4K1Sr4C](https://github.com/Cs4K1Sr4C)这个人提供的，我看过pr了，你们都是刷一些“替换更好看的中文字体”这种commit，[Cs4K1Sr4C](https://github.com/Cs4K1Sr4C)看着也不像是你们项目组的成员（这个项目里没有），并且[Cs4K1Sr4C](https://github.com/Cs4K1Sr4C)本人都没说自己“原创增加i18n”，这个项目算不算是在拾人牙慧？

**Comment by LiuElric** [comment]
- 首先，没有人会搜GPT-Next -Web 这个词，它没有实际的意义，大家不会这么搜
- 如果通过Vercel提供的便利的部署方式为啥不能叫做一键部署呢？简化了部署的门槛呀，不需要再买服务器之类的复杂步骤，基于Vercel能力做有什么错吗？
- 「Cs4K1Sr4C」就是AgentGPT的官方开发同学，拿我们代码提交的。。。可以看这个变量名，这是当时copy我们代码留的commit
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/20209191/234225079-8b714079-e153-4741-b6bf-3a8c9acc0967.png">

**Comment by lzskyline** [comment]
噢～现在你们是想说 Cs4K1Sr4C 偷你们的代码，没有注明也没有给你们Contributor呗？
而且你是怎么得出“拿我们代码提交”这个结论的呢？我看了两个项目，不管是目录结构、常量命名还是翻译内容都不同
<img width="1630" alt="image" src="https://user-images.githubusercontent.com/9845170/234233088-3ffe81f8-0126-44f8-8205-9e0f774e792d.png">
<img width="1765" alt="image" src="https://user-images.githubusercontent.com/9845170/234233071-c24bfd85-aaeb-464e-9a9c-6c0db5359252.png">

所以既不能“一键部署”、翻译也没有被官方采用，甚至还加了很多广告。
如果你们真的想为了“方便大家一键部署”，没这么麻烦，给官方提个pr就行了，他们docker都支持了，增加一个vercel并没有什么太大的成本。
但如果这个项目是为了方便加广告给韭菜星球引流，那就说得通了

**Comment by LiuElric** [comment]
- 可以看看提交内容，他们用的都是我们的变量名。。。以及看看支持的时间，我们在前面支持的
- 官方没做，所以我们快速的做了呀，官方还用的我们的Vercel方案呢，这不是比提pr更直接的贡献
https://github.com/reworkd/AgentGPT/pull/293/files
https://github.com/Dogtiti/AutoGPT-Next-Web/commit/9fce6c4edea02047d94d35b0ac452e894217b92f
![image](https://user-images.githubusercontent.com/20209191/234267282-0f8eebb6-8ea4-45b2-8e28-63853e5cbe06.png)

- 后面是两边的提交时间对比
![image](https://user-images.githubusercontent.com/20209191/234267416-beeddd18-45aa-4dfc-a60d-971f1d926c5e.png)
![image](https://user-images.githubusercontent.com/20209191/234267480-4d77cb5a-8bc7-4162-972f-dbb87d61b97b.png)
