### ISSUE TITLE
和AgentGPT有什么区别

### ISSUE THREAD

**Issue by Ryan-yang125** [Dogtiti/AutoGPT-Next-Web#36]
还有ChatGPT-Next-Web

**Comment by LiuElric** [comment]
感谢关注

- ChatGPT-Next-Web 是基于ChatGPT的能力，直接调用API实现的Web UI能力，AgentGPT是通过LangChain 来构建自己的应用程序和流程控制，能力上不太一样
- AutoGPT-Next-Web 这个项目是来源于 AgentGPT，AgentGPT 其实也是 AutoGPT 的 web UI 版本，我们提供了 i18n 方案以及vercel一键部署能力，更方便大家自己搭建使用
- AgentGPT 的一键部署能力和 i18n 本地化能力也是来源于我们的项目，我们本身也在为 AgentGPT 贡献代码，AgentGPT 官方也邀请加入他们开发团队
- 我们目标是持续输出对国内用户友好的功能和界面（包括但不限于微信登录等），让大家更易用

**Comment by Ryan-yang125** [comment]
感谢回复😊
