### ISSUE TITLE
感觉返回字数有限制

### ISSUE THREAD

**Issue by 573734817pc** [Dogtiti/AutoGPT-Next-Web#53]
返回得文字，比较长得话，就从中间断了，后面得文字就没有返回了。
![image](https://user-images.githubusercontent.com/45155444/234448106-aa0625ed-98e9-4df3-9fb8-7d600883340f.png)

**Comment by LiuElric** [comment]
本质是跟chatGPT在对话，应该是chatgpt也抽风了，我们看看是否可以增加检查机制，续写
