### ISSUE TITLE
OPENAI_API_BASE支持

### ISSUE THREAD

**Issue by chrischjh** [Dogtiti/AutoGPT-Next-Web#58]
发现gpt类相关的开源工具基本上都没有第一时间支持OPENAI_API_BASE这个配置，但在国内这个基本上是刚需

**Comment by Dogtiti** [comment]
收到！今天解决

**Comment by sunguanghui** [comment]
这个OPENAI_API_BASE，需要怎么填写？

1、OPENAI_API_BASE:https://mydomain/v1
2、OPENAI_API_BASE:https://mydomain
3、OPENAI_API_BASE:https://mydomain/v1/chat/completions

在setup.sh的ENV中，以上3种配置，均添加测试过，都提示"访问OpenAI API出错。请检查您的API密钥或稍后重试。"。

是我配置有问题吗？请指导一下，非常感谢！

**Comment by Dogtiti** [comment]
@sunguanghui 看一下详细教程 里面有deno的教程
