### ISSUE TITLE
有没有环境变量可以让agent不要自动continue

### ISSUE THREAD

**Issue by yuanjs** [Dogtiti/AutoGPT-Next-Web#59]
有没有环境变量可以让agent不要自动continue，这样可以暂停agent,
另外从新开始agent, 有记忆吗？

谢谢

**Comment by Dogtiti** [comment]
可以具体说一下使用场景吗

**Comment by yuanjs** [comment]
就是我输入一个目标之后，AI就开始各种自动运行。我看到autogpt缺省运行不是Continuous Mode的，也不建议使用Continuous Mode。
只有在运行的时候加入 --continuous才会是Continuous Mode

主要是有可能会进入死循环，或者觉得有问题的时候，可以让AI不再继续。

还有就是中断agent之后，能否从中断的地方继续，还是只能从头再来。

谢谢

**Comment by LiuElric** [comment]
明白，非常感谢您的建议，我们认真考虑一下哈，可以关注一下我们后续的todolist

**Comment by jebouruama** [comment]
同感，试用的autogpt类应用目前发现ai很容易进入死循环或者执行一些无意义的task，会耗费大量token和时间。目前 [Cognosys](https://app.cognosys.ai/create) 和 [Godmode](https://godmode.space/)都支持分步手动执行task，可控性比较强。但是官方AgentGpt貌似还没有细粒度控制执行task的功能。
我个人认为目前Godmode的实现方式最人性化（当然可能有些繁琐）。用户可对AI拟进行的task计划进行选择，筛选不必要的ai建议task，然后每一步ai都会给出他的想法和原因以及准备做的具体动作，用户批准后方可执行，同时用户可以针对ai建议的task给出反馈（纠偏）。
![CleanShot 2023-04-26 at 18 17 11@2x](https://user-images.githubusercontent.com/44332338/234549333-4e344d0a-373f-45a1-a8bf-4d9491006b0c.png)

**Comment by LiuElric** [comment]
该功能已上线，可以更新一下最新代码，在设置中，可选是否自动执行
