### ISSUE TITLE
这个和AgentGPT有啥区别呀？

### ISSUE THREAD

**Issue by zky001** [Dogtiti/AutoGPT-Next-Web#60]
每台看懂，感觉就是AgentGPT的一个版本？

**Comment by LiuElric** [comment]
项目源自于AgentGPT，AgentGPT项目中的i18n多语言能力以及Vercel部署能力也来源于我们的贡献，我们目标是持续输出对国内友好的功能和界面以及各种部署方案，帮助大家更方便的搭建自己的“AutoGPT”网站
