### ISSUE TITLE
任务已经完成，还是会显示：思考中

### ISSUE THREAD

**Issue by tiwentichat** [Dogtiti/AutoGPT-Next-Web#63]
部署代理程序已经由灰转蓝，停止代理程序按钮也由红转灰，任务实际完成，但是还是思考中，不知道为啥

![auto-gpt-output](https://user-images.githubusercontent.com/125454744/234544191-06107a7b-f954-4f9f-9817-a555e75578f3.png)

**Comment by tiwentichat** [comment]
部署了一个然后体验了下，急求一个功能：主动关闭后，也可以保存记录。

因为autogpt有过度执行任务的嫌疑。有一些内容已经很好了，足以提供好的灵感启发，但是主动关闭的话不出现那个保存按钮也就无法保存到左上角。只能pdf图片或者文本保存。。

这有一丢丢遗憾

**Comment by Dogtiti** [comment]
@tiwentichat 感谢反馈，已添加至TodoList

**Comment by LiuElric** [comment]
最新版本该能力已经支持了，可以更新一下代码查看哈哈
