### ISSUE TITLE
汇总结果

### ISSUE THREAD

**Issue by lloydzhou** [Dogtiti/AutoGPT-Next-Web#78]
### 描述 / Description
1. 如果遇到复杂的任务，子任务会被递归拆分成更细的子任务。
2. 然后结果会散落在很长的消息列表里面。这个时候需要慢慢的找到消息，手动合并，挺麻烦的

### 期望的结果 / Expected Result
希望能在任务完成的时候给出一个按照任务层级归纳查看结果的地方

### 可行性 / Feasibility

1. 更改AutonomousAgent队列，使用一个树形结构来做队列
2. 每次的loop循环总是（广度）递归遍历数结构找到需要被执行的任务
3. 每执行完一个任务，更新任务状态，记录任务结果。开启下一次loop循环
4. 执行完成的时候增加一条合并结果后的消息？

**Comment by lloydzhou** [comment]
> 然后结果会散落在很长的消息列表里面
之所以结果散落在消息列表里面，原因是当前的实现使用队列存储递归的子任务的时候，实际上是模拟使用广度优先方式递归执行任务。所以导致任务顺序混乱

所以，应该有一个简单的方式（创建子任务的时候将子任务放到队列前面）让队列模拟深度优先的方式执行任务。

**Comment by lloydzhou** [comment]
## 期望结果
1. 前面更改子任务执行顺序，只能让执行结果始终保持正确顺序。
2. 但是结果和对应的任务还是错乱的，所以，任务需要有taskId，以便调整消息顺序。（使得聊天窗口从“**日志**窗口”变成真正的**结果**展示窗口）

![image](https://user-images.githubusercontent.com/1826685/234952763-d549074f-f6a9-43da-bf5c-78000a40b81d.png)

**Comment by Dogtiti** [comment]
@LiuElric add to roadmap
