### ISSUE TITLE
Cant trust this

### ISSUE THREAD

**Issue by GreyEnt** [Dogtiti/AutoGPT-Next-Web#79]
I asked to create a scrape of google for information and it made up nearly 95% of sources. Cann;t be trusted for accuracy of finds, also makes up statistics and references. Found it to easily fall off at 50 loops. I asked it to produce documents of all info found, it didn't

Over all, nice interface but doesn't work well in the auto sense.

**Comment by Dogtiti** [comment]
Thank you for the feedback. In fact, we have also noticed this issue and are currently optimizing it, focusing on improving the ability to summarize information to make it more specific and easier to find.

**Comment by GreyEnt** [comment]
thank you for your reply. It's a good solid framework to use. User feedback from a GUI and use POV? Stop it falling off at 50, if is going to, then just get it to find a faster solution or move on whilst loops are low. It also doesn't save its threads and it can't be picked up from the last point. SO it's fun running it but it doesn't produce a document or actual facts. nor will it implement say writing a blog using CGPT and positing it with credentials. It feels much more like a simulation than actually an agent.

**Comment by Dogtiti** [comment]
We have been striving in this direction, and recently we have also developed a roadmap. We look forward to the day when it can accomplish anything you want to give it to do.

**Comment by joostshao** [comment]
i ask it to calculate Kate Elizabeth Winslet's age now(2023), and it failed ~~~~
it  Confused me

**Comment by LiuElric** [comment]
> 我要求它计算凯特伊丽莎白温斯莱特现在的年龄（2023），但它失败了~~~~ 它让我感到困惑

I think you can try again, sometimes you do encounter some errors, I just tried it and he gave me the correct answer

<img width="970" alt="截屏2023-04-29 23 37 47" src="https://user-images.githubusercontent.com/20209191/235311070-5cf47351-039c-47b7-ae2c-4a95d9b3c78e.png">
