### ISSUE TITLE
请问能不能开放调整高级设置

### ISSUE THREAD

**Issue by cakexxx** [Dogtiti/AutoGPT-Next-Web#92]
现在既然已经有NEXT_PUBLIC_GUEST_KEY可以控制访问了，能否在填写NEXT_PUBLIC_GUEST_KEY正确之后就可以更改高级设置，总是有那样的限制用的不够开心。

**Comment by Dogtiti** [comment]
还在考虑访客模式要不要放开高级控制，可以给点建议

**Comment by cakexxx** [comment]
我觉得给了KEY的都是自己人了，甚至是自己了，就给开呗

**Comment by cakexxx** [comment]
我好像又发现一个问题……NEXT_PUBLIC_GUEST_KEY输入了之后仍然没法使用，会显示密匙错误……

**Comment by Dogtiti** [comment]
get , 一会儿我看看，感谢反馈

**Comment by Dogtiti** [comment]
> 我好像又发现一个问题……NEXT_PUBLIC_GUEST_KEY输入了之后仍然没法使用，会显示密匙错误……

这个已修复，更新下代码

**Comment by handsomexiaoyi** [comment]
> 

请问一下，NEXT_PUBLIC_GUEST_KEY这个key在哪里获得
