### ISSUE TITLE
I don't see any difference

### ISSUE THREAD

**Issue by GreyEnt** [Dogtiti/AutoGPT-Next-Web#93]
请在这里描述您的意见、建议、吐槽、鼓励或其他任何想法。我们非常重视您的反馈和意见，感谢您的支持和贡献！
Please describe your opinion, suggestion, complaint, encouragement or any other idea here. We value your feedback and opinions, and appreciate your support and contributions!
## 期望的结果/Expected result
请在这里描述您期望看到的结果或变化。
Please describe the results or changes you would like to see here.
## 声明/statement
请注意，您的问题可能会被公开回复，因此请勿包含任何敏感信息。
Note that your question may be answered publicly, so please do not include any sensitive information.

**Comment by GreyEnt** [comment]
It is still looping, doesn't create text docs to desktop and makes up the figures.  No different to the last version. Stil wont complete tasks and goes off on a long tirade of doing things that it thinks it should. Agent drops off quickly and becomes useless pretty quickly

**Comment by LiuElric** [comment]
You can try some of the latest versions, which increase manual control and can be searched online
